# DO NOT EDIT THIS FILE
#
# Please edit /boot/armbianEnv.txt to set supported parameters
#
# Boot script for the Xunlei WS1508 (Amlogic S805 / meson8b).
#
# ${bootdev} is set by the bootloader before it runs this script: our
# u-boot tries "usb 0", "usb 1", "mmc 0" (SD) and "mmc 1" (eMMC) in that
# order and leaves ${bootdev} pointing at whichever one had a boot.scr.
# Everything below then loads from that same device, so one image boots
# unchanged from USB, SD or internal eMMC.

# We can't use `test -z` due to the bug: https://lists.denx.de/pipermail/u-boot/2005-August/011447.html
if test -n "${bootdev}"; test $? != 0; then
	echo '=============================================================='
	echo 'Please set "bootdev" before calling this script.'
	echo ''
	echo 'Boot from usb:'
	echo '  setenv bootdev "usb 0"'
	echo '  usb start'
	echo '  fatload ${bootdev} 0x12000000 boot.scr && autoscr 0x12000000'
	echo ''
	echo 'Boot from SD card:'
	echo '  setenv bootdev "mmc 0"'
	echo '  fatload ${bootdev} 0x12000000 boot.scr && autoscr 0x12000000'
	echo ''
	echo 'Boot from eMMC:'
	echo '  setenv bootdev "mmc 1"'
	echo '  fatload ${bootdev} 0x12000000 boot.scr && autoscr 0x12000000'
	echo '=============================================================='
	exit 22
fi

echo "Try to boot from ${bootdev}"

# Snapshot the bootloader's storage detection before armbianEnv.txt is
# imported. "env import" without -d overwrites existing definitions
# (common/cmd_nvedit.c:710), so a "store=" line in a file the user edits
# would otherwise replace the value set_storage_device_flag() worked out
# from the hardware - and every decision below that trusts ${store} would
# be trusting the file instead of the board.
setenv ws1508_store "${store}"

fatload ${bootdev} 0x11000000 /armbianEnv.txt && env import -t 0x11000000 ${filesize}

if test -n "${rootdev}"; test $? != 0; then
	echo 'Please set "rootdev" before calling this script'
	echo 'or set it in armbianEnv.txt.'
	exit 22
fi

if test -n "${consoleargs}"; test $? != 0; then
	test -n "${console}" || setenv console "both"

	setenv consoleargs ""
	# Due to https://github.com/systemd/systemd/issues/9899, only the last
	#   console will be the primary console (/dev/console) which is the
	#   only console the initramfs shell and the systemd log use.
	# So when set "both", we use serial console as the primary console.
	test "${console}" = "display" || test "${console}" = "both" && setenv consoleargs "${consoleargs} console=tty1"
	test "${console}" = "serial" || test "${console}" = "both" && setenv consoleargs "${consoleargs} console=ttyAML0,115200n8"
	setenv consoleargs "${consoleargs} no_console_suspend consoleblank=0"

	test -n "${bootlogo}" || setenv bootlogo "false"
	if test "${bootlogo}" = "true"; then
		setenv consoleargs "${consoleargs} splash plymouth.ignore-serial-consoles"
	else
		setenv consoleargs "${consoleargs} splash=verbose"
	fi
fi

# Boot Arguments
setenv bootargs ""
setenv bootargs "${bootargs} root=${rootdev} rootwait rw"
setenv bootargs "${bootargs} ${consoleargs}"
setenv bootargs "${bootargs} ${extraargs}"

# Carry the bootloader's storage detection into the running system, so
# "which variant is this, and did the bootloader find its flash?" can be
# answered over SSH instead of needing a soldering iron and a USB-TTL
# adapter. ${store} is set by set_storage_device_flag() before bootcmd:
# 1 = NAND, 2 = eMMC, 3 = nothing detected. ws1508-info decodes it.
setenv bootargs "${bootargs} ws1508.store=${ws1508_store}"

# Booting.
#
# Load addresses matter on this board. DRAM starts at 0x0 and the WS1508
# has 512MB, so anything at or above 0x20000000 is past the end of RAM.
# The OneCloud script these addresses came from uses 0x20800000 /
# 0x21800000 / 0x22000000, which is fine on its 1GB but lands in thin air
# here -- and not merely "unbacked": update_ddr_mmu_table() zeroes the
# first-level descriptor for every 1MB section beyond the auto-detected
# size, so a load there takes a translation fault and u-boot dies.
#
# Four regions in the low 512MB are already spoken for by u-boot's own
# environment, so the loads below step around them:
#   0x10000000 (256MB)  u-boot itself (CONFIG_SYS_TEXT_BASE) + 12MB malloc
#   0x12000000 (288MB)  ${loadaddr}: boot.scr, i.e. THIS script, still
#                       executing out of that buffer for as long as it runs
#   0x13000000 (304MB)  ${loadaddr_logo}, used by "imgread pic resource"
#   0x15100000 (337MB)  ${fb_addr}, the framebuffer (~2.7MB at 1280x720x24)
#
#   0x11000000 (272MB)  armbianEnv.txt scratch (small, read once)
#   0x16000000 (352MB)  uImage        -- 64MB of headroom, clear of fb_addr
#   0x1a000000 (416MB)  dtb
#   0x1a800000 (424MB)  uInitrd       -- ~88MB left below the 512MB mark
#
# bootm then relocates the kernel down to the load address in the uImage
# header (Armbian builds meson with LOADADDR=0x00208000) and moves the
# fdt/initrd within the bootmap, which CONFIG_SYS_BOOTMAPSZ caps at the
# real 512MB.

# Which device tree to load.
#
# The default is the eMMC variant, which is also the right thing on a NAND
# unit: there the SD/eMMC controller simply finds no card, and everything
# else on the board is identical. A NAND unit that wants its internal
# flash visible as a read-only /dev/mtd0 sets
#
#   fdtfile=meson8b-ws1508-nand.dtb
#
# in armbianEnv.txt. That is deliberately NOT selected automatically from
# ${store}: enabling the NAND controller makes the kernel run nand_scan()
# over the vendor flash with a driver that has never been exercised on
# this silicon, and nobody should get that without asking for it.
#
# It does not make the box boot from NAND either, but not for the reason
# this comment used to give. This bootloader CAN read raw NAND: "store
# read <name> <addr> <off> <size>" forwards to "amlnf read_byte" on a
# NAND unit, which is how the vendor firmware boots. What it lacks is a
# filesystem layer over NAND (CONFIG_NEXT_NAND drops libmtd.o/libnand.o),
# so fatload cannot work there -- and this script has no store-read
# branch. Every load below is a fatload from ${bootdev}. Booting from
# internal NAND is unimplemented here, not impossible; it would need a
# store-read variant of these three loads plus offsets that match the
# vendor partition table, and a rootfs story Linux does not have yet.
#
# Nothing but the user is expected to write this variable: Armbian
# appends an fdtfile= line to armbianEnv.txt when the board config sets
# BOOT_FDT_FILE, and ws1508.conf deliberately does not. That is read from
# Armbian's bootscript handling and has not been re-verified against a
# checkout in this tree, so if a future Armbian starts emitting the line
# unconditionally, the default dtb below stops being the default -- worth
# checking if an eMMC unit ever comes up with the NAND dtb. `test -z` is
# broken in this u-boot, hence the `test -n ... ||` form used elsewhere.
test -n "${fdtfile}" || setenv fdtfile meson8b-ws1508.dtb

# Refuse the NAND device tree on a unit whose own bootloader did not find
# raw NAND. meson8b-ws1508-nand.dts sets &sdhc to disabled, so on an eMMC
# unit that dtb removes the very controller the rootfs lives behind: the
# kernel boots and then panics with no root device. Recovery is a USB
# stick (u-boot tries USB first), not a card reader - eMMC is soldered.
# ${store} is the bootloader's own detection result and costs nothing to
# consult, so a typo in armbianEnv.txt degrades to "the NAND dtb was
# ignored" instead of "the box no longer boots". Chained `test ... &&`
# rather than `if`, matching the form used above; `test -z` is broken in
# this u-boot.
test "${fdtfile}" = "meson8b-ws1508-nand.dtb" && test "${ws1508_store}" != "1" && echo "ws1508: ${fdtfile} needs a raw-NAND unit (store=${ws1508_store}) - falling back to meson8b-ws1508.dtb" && setenv fdtfile meson8b-ws1508.dtb

fatload ${bootdev} 0x16000000 /uImage || exit 1
fatload ${bootdev} 0x1a800000 /uInitrd || exit 1
fatload ${bootdev} 0x1a000000 /dtb/${fdtfile} || exit 1

bootm 0x16000000 0x1a800000 0x1a000000

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
