#!/usr/bin/env bash
#
# Build the WS1508 Armbian image using the upstream armbian/build framework.
#
# Everything WS1508-specific is delivered through userpatches/, which
# Armbian searches ahead of its own tree for board configs, boot scripts,
# boot environments and kernel patches. Nothing in the Armbian checkout is
# modified, so bumping ARMBIAN_REF does not create conflicts.
#
# Usage:
#   scripts/build-armbian.sh [kernel|build]
#     kernel  build only the kernel .debs (useful to cache them in CI)
#     build   build the full image (default)

source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

MODE="${1:-build}"
ARMBIAN_SRC="${WORKDIR}/armbian-build"

mkdir -p "${WORKDIR}" "${OUTDIR}"

if [[ ! -d "${ARMBIAN_SRC}/.git" ]]; then
	log "Cloning ${ARMBIAN_REPO} @ ${ARMBIAN_REF}"
	git clone --depth 1 --branch "${ARMBIAN_REF}" "${ARMBIAN_REPO}" "${ARMBIAN_SRC}" 2>/dev/null \
		|| git clone --depth 1 "${ARMBIAN_REPO}" "${ARMBIAN_SRC}"
fi

log "Installing WS1508 userpatches into the Armbian checkout"
mkdir -p "${ARMBIAN_SRC}/userpatches"
cp -a "${REPO_ROOT}/userpatches/." "${ARMBIAN_SRC}/userpatches/"
chmod +x "${ARMBIAN_SRC}/userpatches/customize-image.sh"

# Hand the image-customisation settings to customize-image.sh through
# userpatches/overlay, which Armbian bind-mounts at /tmp/overlay inside the
# image chroot. See the comment at the top of customize-image.sh for why
# this is preferred over exporting environment variables.
mkdir -p "${ARMBIAN_SRC}/userpatches/overlay"
{
	echo "# Generated by scripts/build-armbian.sh - do not edit by hand."
	for var in WS1508_ROOT_PASSWORD WS1508_SSH_AUTHORIZED_KEY \
	           WS1508_ROOT_PASSWORD_LOGIN WS1508_HOSTNAME \
	           WS1508_TIMEZONE WS1508_EXTRA_PACKAGES; do
		if [[ -n "${!var:-}" ]]; then
			printf '%s=%q\n' "${var}" "${!var}"
		fi
	done
} > "${ARMBIAN_SRC}/userpatches/overlay/ws1508-build.conf"
chmod 600 "${ARMBIAN_SRC}/userpatches/overlay/ws1508-build.conf"

# Armbian derives the kernel patch directory from the family's kernel
# version: archive/${LINUXFAMILY}-${KERNEL_MAJOR_MINOR}. Our device tree
# lives in userpatches/kernel/archive/meson-6.12. If Armbian moves the
# meson family to a different kernel, that directory stops being consulted
# and the WS1508 dtb silently vanishes from the image -- so detect the
# version actually configured upstream and mirror the directory across.
detect_kernel_major_minor() {
	local family_inc="${ARMBIAN_SRC}/config/sources/families/include/meson_common.inc"
	[[ -f "${family_inc}" ]] || return 1
	sed -n 's/.*KERNEL_MAJOR_MINOR="\([0-9.]*\)".*/\1/p' "${family_inc}" | head -1
}

WANTED_KMM="$(detect_kernel_major_minor || true)"
if [[ -n "${WANTED_KMM}" && ! -d "${ARMBIAN_SRC}/userpatches/kernel/archive/meson-${WANTED_KMM}" ]]; then
	warn "Armbian's meson family now targets kernel ${WANTED_KMM}, but this repo ships the device tree under meson-6.12."
	warn "Mirroring it to meson-${WANTED_KMM} so the WS1508 dtb is still built. Review the DTS against that kernel."
	cp -a "${ARMBIAN_SRC}/userpatches/kernel/archive/meson-6.12" \
	      "${ARMBIAN_SRC}/userpatches/kernel/archive/meson-${WANTED_KMM}"
fi

# Armbian refuses to run as root unless told, and its own CI detection
# changes behaviour in ways that break a plain `compile.sh` invocation.
export GITHUB_ACTIONS=false

COMMON_ARGS=(
	ALLOW_ROOT=yes
	BOARD="${BOARD}"
	BRANCH="${BRANCH}"
	EXPERT=yes
	USE_CCACHE=no
)

case "${MODE}" in
	kernel)
		log "Building kernel packages for ${BOARD} (${BRANCH})"
		( cd "${ARMBIAN_SRC}" && ./compile.sh kernel "${COMMON_ARGS[@]}" )
		;;
	build)
		log "Building image: BOARD=${BOARD} BRANCH=${BRANCH} RELEASE=${RELEASE} MINIMAL=${BUILD_MINIMAL}"
		( cd "${ARMBIAN_SRC}" && ./compile.sh build \
			"${COMMON_ARGS[@]}" \
			RELEASE="${RELEASE}" \
			KERNEL_CONFIGURE=no \
			BUILD_MINIMAL="${BUILD_MINIMAL}" \
			BUILD_DESKTOP=no \
			SKIP_EXTERNAL_TOOLCHAINS=yes \
			CLEAN_LEVEL= \
			COMPRESS_OUTPUTIMAGE=img )
		;;
	*)
		die "Unknown mode '${MODE}'. Use 'kernel' or 'build'."
		;;
esac

# compile.sh runs under sudo; hand the results back to the calling user.
if [[ -n "${SUDO_UID:-}" ]]; then
	chown -R "${SUDO_UID}:${SUDO_GID:-${SUDO_UID}}" "${ARMBIAN_SRC}/output" 2>/dev/null || true
fi

mkdir -p "${OUTDIR}/images" "${OUTDIR}/debs"
shopt -s nullglob
for f in "${ARMBIAN_SRC}"/output/images/*; do cp -a "$f" "${OUTDIR}/images/"; done
for f in "${ARMBIAN_SRC}"/output/debs/*.deb;  do cp -a "$f" "${OUTDIR}/debs/";   done
shopt -u nullglob

log "Armbian output:"
ls -la "${OUTDIR}/images" 2>/dev/null || true

# A WS1508 image without the WS1508 dtb boots nowhere: the boot script
# loads /dtb/meson8b-ws1508.dtb unconditionally. Catch that here rather
# than after somebody flashes it.
if [[ "${MODE}" == "build" ]]; then
	# Pick the raw Armbian image, not a *.burn.img left over from an
	# earlier run in the same output directory -- that also matches *.img,
	# sorts first, and is not a partitioned disk image, so mounting it
	# would fail and abort a perfectly good build.
	img=""
	shopt -s nullglob
	for f in "${OUTDIR}"/images/*.img; do
		case "${f}" in *.burn.img) continue ;; esac
		img="${f}"
		break
	done
	shopt -u nullglob

	if [[ -n "${img}" ]]; then
		log "Verifying the image contains meson8b-ws1508.dtb"
		# Attach the boot partition by explicit offset rather than with
		# --partscan: the /dev/loopNpM nodes it relies on come from udev,
		# which is absent in many build containers, and there the mount
		# below would fail for a reason that has nothing to do with the
		# image. Offsets come from the MBR, same as make-burn-image.sh.
		start_lba="$(python3 - "${img}" <<-'PY'
			import struct, sys
			with open(sys.argv[1], 'rb') as f:
			    mbr = f.read(512)
			if mbr[510:512] != b'\x55\xaa':
			    sys.exit('not an MBR-partitioned image')
			e = mbr[446:462]
			start, sectors = struct.unpack_from('<II', e, 8)
			if e[4] == 0 or not sectors:
			    sys.exit('no first partition')
			print(start)
		PY
		)" || die "Cannot read the partition table of ${img}: ${start_lba}"

		loop="$(losetup --find --show --offset "$((start_lba * 512))" "${img}")"
		mnt="$(mktemp -d)"
		trap 'umount "${mnt}" 2>/dev/null || true; losetup -d "${loop}" 2>/dev/null || true' EXIT
		mount -o ro "${loop}" "${mnt}"
		[[ -f "${mnt}/dtb/meson8b-ws1508.dtb" ]] \
			|| die "Image is missing /dtb/meson8b-ws1508.dtb - the DT autopatcher did not run. Refusing to publish."
		[[ -f "${mnt}/boot.scr" ]] \
			|| die "Image is missing /boot.scr - the bootloader would find nothing to run."
		[[ -f "${mnt}/uInitrd" ]] \
			|| die "Image is missing /uInitrd - boot-ws1508.cmd loads it unconditionally and would abort."
		log "Verified: meson8b-ws1508.dtb, boot.scr and uInitrd are present in the boot partition"
		umount "${mnt}"
		losetup -d "${loop}"
		trap - EXIT
	fi
fi
